### PR TITLE
Adds real code to test_package

### PR DESCRIPTION
**Pull request by danimtb**
This ensures package is linkable in static and shared options

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Fine by me! This improves the test just enough to actually verify linking without rendering it fragile with too many intricacies. One OSX job has already failed, but that's ok, since it was just a connectivity issue. The xcode 8.2 job will also fail, because of the issue we have been discussing on slack (retired image). We have to remove the 8.2 image before submitting this to stable. But I think we can accept the PR first, cancel any builds that get launched, remove the 8.2 image, and launch the final build.

**Comment by solvingj** [comment]
In future please submit PRs to test branch. @dimi309 pls merge back to test branch and push. I would but on mobile.

**Comment by ghost** [comment]
Sadly, I don't have access to my environment either right now. I'll merge when I'm with my computer 💻

**Comment by ghost** [comment]
As discussed, I've merged this to the testing/3.2.1 branch, also removing the xcode 8.2 image: https://github.com/bincrafters/conan-glfw/commits/testing/3.2.1

**Comment by danimtb** [comment]
Thank you @dimi309 and @solvingj!

**Pull request closed without merging**
